package com.mass.dao;

import com.mass.dto.ApplyOrgTemp;
import com.mass.dto.login.ApplyDTO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ApplyOrgTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_org_temp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_org_temp
     *
     * @mbggenerated
     */
    int insert(ApplyOrgTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_org_temp
     *
     * @mbggenerated
     */
    int insertSelective(ApplyOrgTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_org_temp
     *
     * @mbggenerated
     */
    ApplyOrgTemp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_org_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApplyOrgTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_org_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApplyOrgTemp record);

    int getusernameandorgid(ApplyDTO applyOrgTemp);

    List<ApplyOrgTemp> getByStatus(@Param("status") int i);

    Integer getByStatusCount(@Param("status") Integer status);

    void upStatusById(@Param("id") Long id, @Param("status") Integer status);

    List<ApplyOrgTemp> seeApplymyList(@Param("sno") String username, @Param("status") Integer status);

    Integer insertApplyDto(ApplyDTO applyOrgTemp);
}