package com.mass.dao;

import com.mass.dto.SysOrganization;
import com.mass.dto.SysOrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated
     */
    int insert(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated
     */
    int insertSelective(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated
     */
   SysOrganization selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysOrganization record);
   public  List<SysOrganization> getAll();

    public  Integer getAllCount();

   public Integer getOrgByOrgNameCount(@Param("orgName")String orgname);

     public SysOrganization getUserOrgByID(@Param("orgId")Long id);

     List<SysOrganization> getByuserName(String userName);
     SysOrganization getMyManage(String usereName);

    SysOrganization getOneByOrgName(@Param("orgName")String orgName);

    void delById(@Param("id") Long id);

    void updateOrgByID(@Param("username") String username, @Param("name")String name, @Param("orgId")Long orgId);

    int userIsPresent(@Param("username")String username,@Param("orgId")Long orgId);
}