package com.mass.dto;

import com.mass.util.NotNull;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

public class ApplyOrgTemp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.name
     *
     * @mbggenerated
     */
    @ApiModelProperty("社团名称")
    @NotNull(message = "社团名称")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.pet_name
     *
     * @mbggenerated
     */
    @ApiModelProperty("社团别名")
    @NotNull(message = "社团别名")
    private String petName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.logo_url
     *
     * @mbggenerated
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.president_name
     *
     * @mbggenerated
     */
    @ApiModelProperty("社长")
    @NotNull(message = "社长")
    private String presidentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.president_sno
     *
     * @mbggenerated
     */
    @ApiModelProperty("社长学号")
    @NotNull(message = "社长学号")
    private String presidentSno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.stastus
     *
     * @mbggenerated
     */
    private Byte stastus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.reason
     *
     * @mbggenerated
     */
    @ApiModelProperty("申请理由")
    @NotNull(message = "申请理由")
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.usno1
     *
     * @mbggenerated
     */
    @ApiModelProperty("成员1")
    @NotNull(message = "成员1")
    private String usno1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.usno2
     *
     * @mbggenerated
     */
    @ApiModelProperty("成员2")
    @NotNull(message = "成员2")
    private String usno2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.usno3
     *
     * @mbggenerated
     */
    @ApiModelProperty("成员3")
    @NotNull(message = "成员3")
    private String usno3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.id
     *
     * @return the value of apply_org_temp.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.id
     *
     * @param id the value for apply_org_temp.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.name
     *
     * @return the value of apply_org_temp.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.name
     *
     * @param name the value for apply_org_temp.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.pet_name
     *
     * @return the value of apply_org_temp.pet_name
     *
     * @mbggenerated
     */
    public String getPetName() {
        return petName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.pet_name
     *
     * @param petName the value for apply_org_temp.pet_name
     *
     * @mbggenerated
     */
    public void setPetName(String petName) {
        this.petName = petName == null ? null : petName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.logo_url
     *
     * @return the value of apply_org_temp.logo_url
     *
     * @mbggenerated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.logo_url
     *
     * @param logoUrl the value for apply_org_temp.logo_url
     *
     * @mbggenerated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.president_name
     *
     * @return the value of apply_org_temp.president_name
     *
     * @mbggenerated
     */
    public String getPresidentName() {
        return presidentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.president_name
     *
     * @param presidentName the value for apply_org_temp.president_name
     *
     * @mbggenerated
     */
    public void setPresidentName(String presidentName) {
        this.presidentName = presidentName == null ? null : presidentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.president_sno
     *
     * @return the value of apply_org_temp.president_sno
     *
     * @mbggenerated
     */
    public String getPresidentSno() {
        return presidentSno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.president_sno
     *
     * @param presidentSno the value for apply_org_temp.president_sno
     *
     * @mbggenerated
     */
    public void setPresidentSno(String presidentSno) {
        this.presidentSno = presidentSno == null ? null : presidentSno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.stastus
     *
     * @return the value of apply_org_temp.stastus
     *
     * @mbggenerated
     */
    public Byte getStastus() {
        return stastus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.stastus
     *
     * @param stastus the value for apply_org_temp.stastus
     *
     * @mbggenerated
     */
    public void setStastus(Byte stastus) {
        this.stastus = stastus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.update_time
     *
     * @return the value of apply_org_temp.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.update_time
     *
     * @param updateTime the value for apply_org_temp.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.create_time
     *
     * @return the value of apply_org_temp.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.create_time
     *
     * @param createTime the value for apply_org_temp.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.reason
     *
     * @return the value of apply_org_temp.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.reason
     *
     * @param reason the value for apply_org_temp.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.usno1
     *
     * @return the value of apply_org_temp.usno1
     *
     * @mbggenerated
     */
    public String getUsno1() {
        return usno1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.usno1
     *
     * @param usno1 the value for apply_org_temp.usno1
     *
     * @mbggenerated
     */
    public void setUsno1(String usno1) {
        this.usno1 = usno1 == null ? null : usno1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.usno2
     *
     * @return the value of apply_org_temp.usno2
     *
     * @mbggenerated
     */
    public String getUsno2() {
        return usno2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.usno2
     *
     * @param usno2 the value for apply_org_temp.usno2
     *
     * @mbggenerated
     */
    public void setUsno2(String usno2) {
        this.usno2 = usno2 == null ? null : usno2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_org_temp.usno3
     *
     * @return the value of apply_org_temp.usno3
     *
     * @mbggenerated
     */
    public String getUsno3() {
        return usno3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_org_temp.usno3
     *
     * @param usno3 the value for apply_org_temp.usno3
     *
     * @mbggenerated
     */
    public void setUsno3(String usno3) {
        this.usno3 = usno3 == null ? null : usno3.trim();
    }
}