package com.mass.dto;

import java.util.Date;

public class RoleResMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res_menu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res_menu.reseouce_id
     *
     * @mbggenerated
     */
    private Integer reseouceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res_menu.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res_menu.res_menu
     *
     * @mbggenerated
     */
    private String resMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res_menu.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res_menu.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res_menu.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res_menu.id
     *
     * @return the value of role_res_menu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res_menu.id
     *
     * @param id the value for role_res_menu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res_menu.reseouce_id
     *
     * @return the value of role_res_menu.reseouce_id
     *
     * @mbggenerated
     */
    public Integer getReseouceId() {
        return reseouceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res_menu.reseouce_id
     *
     * @param reseouceId the value for role_res_menu.reseouce_id
     *
     * @mbggenerated
     */
    public void setReseouceId(Integer reseouceId) {
        this.reseouceId = reseouceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res_menu.role_id
     *
     * @return the value of role_res_menu.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res_menu.role_id
     *
     * @param roleId the value for role_res_menu.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res_menu.res_menu
     *
     * @return the value of role_res_menu.res_menu
     *
     * @mbggenerated
     */
    public String getResMenu() {
        return resMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res_menu.res_menu
     *
     * @param resMenu the value for role_res_menu.res_menu
     *
     * @mbggenerated
     */
    public void setResMenu(String resMenu) {
        this.resMenu = resMenu == null ? null : resMenu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res_menu.role_name
     *
     * @return the value of role_res_menu.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res_menu.role_name
     *
     * @param roleName the value for role_res_menu.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res_menu.update_time
     *
     * @return the value of role_res_menu.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res_menu.update_time
     *
     * @param updateTime the value for role_res_menu.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res_menu.create_time
     *
     * @return the value of role_res_menu.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res_menu.create_time
     *
     * @param createTime the value for role_res_menu.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}