package com.mass.dto.login;

import com.mass.util.NotNull;
import io.swagger.annotations.ApiModelProperty;

public class ApplyDTO {
    @ApiModelProperty("社团名称")
    @NotNull(message = "社团名称")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.pet_name
     *
     * @mbggenerated
     */
    @ApiModelProperty("社团别名")
    @NotNull(message = "社团别名")
    private String petName;
    @ApiModelProperty("社长")
    @NotNull(message = "社长")
    private String presidentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.president_sno
     *
     * @mbggenerated
     */
    @ApiModelProperty("社长学号")
    @NotNull(message = "社长学号")
    private String presidentSno;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.reason
     *
     * @mbggenerated
     */
    @ApiModelProperty("申请理由")
    @NotNull(message = "申请理由")
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.usno1
     *
     * @mbggenerated
     */
    @ApiModelProperty("成员1")
    @NotNull(message = "成员1")
    private String usno1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.usno2
     *
     * @mbggenerated
     */
    @ApiModelProperty("成员2")
    @NotNull(message = "成员2")
    private String usno2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_org_temp.usno3
     *
     * @mbggenerated
     */
    @ApiModelProperty("成员3")
    @NotNull(message = "成员3")
    private String usno3;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPetName() {
        return petName;
    }

    public void setPetName(String petName) {
        this.petName = petName;
    }

    public String getPresidentName() {
        return presidentName;
    }

    public void setPresidentName(String presidentName) {
        this.presidentName = presidentName;
    }

    public String getPresidentSno() {
        return presidentSno;
    }

    public void setPresidentSno(String presidentSno) {
        this.presidentSno = presidentSno;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getUsno1() {
        return usno1;
    }

    public void setUsno1(String usno1) {
        this.usno1 = usno1;
    }

    public String getUsno2() {
        return usno2;
    }

    public void setUsno2(String usno2) {
        this.usno2 = usno2;
    }

    public String getUsno3() {
        return usno3;
    }

    public void setUsno3(String usno3) {
        this.usno3 = usno3;
    }
}
